# Generated by Django 5.1.3 on 2024-11-22 18:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_expense_date_alter_expense_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='expense',
            name='salary',
            field=models.IntegerField(default=0),
        ),
    ]
