# Generated by Django 5.1.3 on 2024-11-28 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_expense_date_alter_expense_salary'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='record_type',
            field=models.CharField(choices=[('expense', 'Трата'), ('income', 'Прибыль')], default='expense', max_length=7),
        ),
    ]
