# Generated by Django 5.1.3 on 2024-11-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_expense_record_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['date']},
        ),
    ]
