# Generated by Django 5.1.3 on 2024-11-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_expense_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='expense',
            options={'ordering': ['-date']},
        ),
        migrations.AlterField(
            model_name='expense',
            name='record_type',
            field=models.CharField(choices=[('expense', 'Расход'), ('income', 'Доход')], default='expense', max_length=7),
        ),
    ]
