# Generated by Django 5.1.3 on 2024-12-01 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_expense_options_alter_expense_record_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='salary',
        ),
    ]
